# profiles.yml pour dbt (ClickHouse)
# Placez ce fichier dans %USERPROFILE%\.dbt\profiles.yml pour un usage global
# Ou conservez ce fichier dans le projet et exportez la variable DBT_PROFILES_DIR si nécessaire.

bikelocal:
  target: "{{ env_var('DBT_TARGET', 'clickhouse') }}"
  outputs:
    clickhouse:
      type: clickhouse
      threads: 4
      # Reads connection values from environment variables (use .env or export vars)
      host: "{{ env_var('CLICKHOUSE_HOST', 'host.docker.internal') }}"
      port: {{ env_var('CLICKHOUSE_PORT', 8123) | int }}
      user: "{{ env_var('CLICKHOUSE_USER', 'default') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD', '') }}"
      database: "{{ env_var('CLICKHOUSE_DATABASE', 'localbike_raw') }}"
      schema: "{{ env_var('CLICKHOUSE_DATABASE', 'localbike_raw') }}"
      secure: false
      protocol: http

# Exemples d'utilisation des variables d'environnement (PowerShell)
# $env:CLICKHOUSE_HOST='host.docker.internal'
# $env:CLICKHOUSE_PORT='8123'
# $env:CLICKHOUSE_USER='airbyte_ch'
# $env:CLICKHOUSE_PASSWORD='f!LVd7jzgmBCDwSZp9yu'

# Pour vérifier la connexion depuis le projet :
# 1) Activez votre venv : .\.venv_dbt\Scripts\Activate.ps1
# 2) dbt debug --profiles-dir .
